fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile.git"
    vcsrepo: "https://github.com/puppetlabs/puppetlabs-vcsrepo.git"
  symlinks:
    jenkins_job_builder: "#{source_dir}"
