name          'opentable-jenkins_job_builder'
version       '0.1.0'
source        'git://github.com/opentable/puppet-jenkins_job_builder.git'
author        'puppet'
license       'Apache License, Version 2.0'
summary       'Module for managing the openstack jenkins_job_builder tool'
description   'The openstack jenkins_job_builder tool manages the configuration of jobs in your Jenkins instance'
project_page  'https://github.com/opentable/puppet-jenkins_job_builder'
dependency    'puppetlabs/stdlib', '>=3.0.0'
